import React from 'react';
import { useEffect, useState } from "react";
import api from "../services/api";

export default function Notifications(){
  const [items,setItems]=useState([]);
  useEffect(()=>{api.get("/notifications").then(r=>setItems(r.data));},[]);
  return <>
    <div className="page-heading"><div><h2>Notifications</h2><p>Mock email/SMS notifications generated by CRM events.</p></div></div>
    <div className="panel table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Recipient</th><th>Subject</th><th>Status</th></tr></thead><tbody>
      {items.map(x=><tr key={x._id}><td>{new Date(x.createdAt).toLocaleString()}</td><td>{x.type.toUpperCase()}</td><td>{x.recipient}</td><td>{x.subject}</td><td><span className="badge won">{x.status}</span></td></tr>)}
      {!items.length&&<tr><td colSpan="5" className="empty">No notifications yet.</td></tr>}
    </tbody></table></div>
  </>;
}
